CREATE TABLE IF NOT EXISTS user (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	token VARCHAR(500) NOT NULL
	
) ENGINE = InnoDB DEFAULT CHARSET = utf8;